apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubelet-csr-approver
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infra
  source:
    chart: kubelet-csr-approver
    helm:
      values: |-
        metrics:
          enable: false
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
        env:
          - name: BYPASS_DNS_RESOLUTION
            value: "true"
    repoURL: https://postfinance.github.io/kubelet-csr-approver
    targetRevision: 1.2.2
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
