apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: infra/rbac
    repoURL: git@github.com:lbogdan/k8s-workshop-gitops.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
