apiVersion: v1
kind: Namespace
metadata:
  name: andacristea
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: andacristea
  namespace: andacristea
---
apiVersion: v1
kind: Secret
metadata:
  name: andacristea-token
  namespace: andacristea
  annotations:
    kubernetes.io/service-account.name: andacristea
type: kubernetes.io/service-account-token
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: andacristea
  namespace: andacristea
subjects:
- kind: ServiceAccount
  name: andacristea
  namespace: andacristea
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: andacristea-view
subjects:
- kind: ServiceAccount
  name: andacristea
  namespace: andacristea
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: andacristea-nodes-read
subjects:
- kind: ServiceAccount
  name: andacristea
  namespace: andacristea
roleRef:
  kind: ClusterRole
  name: nodes-read
  apiGroup: rbac.authorization.k8s.io
