apiVersion: v1
kind: Namespace
metadata:
  name: anton
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: anton
  namespace: anton
---
apiVersion: v1
kind: Secret
metadata:
  name: anton-token
  namespace: anton
  annotations:
    kubernetes.io/service-account.name: anton
type: kubernetes.io/service-account-token
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: anton
  namespace: anton
subjects:
- kind: ServiceAccount
  name: anton
  namespace: anton
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: anton-view
subjects:
- kind: ServiceAccount
  name: anton
  namespace: anton
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: anton-nodes-read
subjects:
- kind: ServiceAccount
  name: anton
  namespace: anton
roleRef:
  kind: ClusterRole
  name: nodes-read
  apiGroup: rbac.authorization.k8s.io
