apiVersion: v1
kind: Namespace
metadata:
  name: lbogdan
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lbogdan
  namespace: lbogdan
---
apiVersion: v1
kind: Secret
metadata:
  name: lbogdan-token
  namespace: lbogdan
  annotations:
    kubernetes.io/service-account.name: lbogdan
type: kubernetes.io/service-account-token
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lbogdan
  namespace: lbogdan
subjects:
- kind: ServiceAccount
  name: lbogdan
  namespace: lbogdan
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lbogdan-view
subjects:
- kind: ServiceAccount
  name: lbogdan
  namespace: lbogdan
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lbogdan-nodes-read
subjects:
- kind: ServiceAccount
  name: lbogdan
  namespace: lbogdan
roleRef:
  kind: ClusterRole
  name: nodes-read
  apiGroup: rbac.authorization.k8s.io
