apiVersion: v1
kind: Namespace
metadata:
  name: mariusconstantinit
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariusconstantinit
  namespace: mariusconstantinit
---
apiVersion: v1
kind: Secret
metadata:
  name: mariusconstantinit-token
  namespace: mariusconstantinit
  annotations:
    kubernetes.io/service-account.name: mariusconstantinit
type: kubernetes.io/service-account-token
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mariusconstantinit
  namespace: mariusconstantinit
subjects:
- kind: ServiceAccount
  name: mariusconstantinit
  namespace: mariusconstantinit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mariusconstantinit-view
subjects:
- kind: ServiceAccount
  name: mariusconstantinit
  namespace: mariusconstantinit
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mariusconstantinit-nodes-read
subjects:
- kind: ServiceAccount
  name: mariusconstantinit
  namespace: mariusconstantinit
roleRef:
  kind: ClusterRole
  name: nodes-read
  apiGroup: rbac.authorization.k8s.io
