apiVersion: v1
kind: Namespace
metadata:
  name: putharu
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: putharu
  namespace: putharu
---
apiVersion: v1
kind: Secret
metadata:
  name: putharu-token
  namespace: putharu
  annotations:
    kubernetes.io/service-account.name: putharu
type: kubernetes.io/service-account-token
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: putharu
  namespace: putharu
subjects:
- kind: ServiceAccount
  name: putharu
  namespace: putharu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: putharu-view
subjects:
- kind: ServiceAccount
  name: putharu
  namespace: putharu
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: putharu-nodes-read
subjects:
- kind: ServiceAccount
  name: putharu
  namespace: putharu
roleRef:
  kind: ClusterRole
  name: nodes-read
  apiGroup: rbac.authorization.k8s.io
