apiVersion: v1
kind: Namespace
metadata:
  name: ralucaantemir
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ralucaantemir
  namespace: ralucaantemir
---
apiVersion: v1
kind: Secret
metadata:
  name: ralucaantemir-token
  namespace: ralucaantemir
  annotations:
    kubernetes.io/service-account.name: ralucaantemir
type: kubernetes.io/service-account-token
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ralucaantemir
  namespace: ralucaantemir
subjects:
- kind: ServiceAccount
  name: ralucaantemir
  namespace: ralucaantemir
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ralucaantemir-view
subjects:
- kind: ServiceAccount
  name: ralucaantemir
  namespace: ralucaantemir
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ralucaantemir-nodes-read
subjects:
- kind: ServiceAccount
  name: ralucaantemir
  namespace: ralucaantemir
roleRef:
  kind: ClusterRole
  name: nodes-read
  apiGroup: rbac.authorization.k8s.io
